apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: {{ include "rollout-app.fullname" . }}
  labels:
    {{- include "rollout-app.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      {{- include "rollout-app.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "rollout-app.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
  strategy:
    blueGreen:
      activeService: {{ .Values.rollout.strategy.blueGreen.activeService }}
      previewService: {{ .Values.rollout.strategy.blueGreen.previewService }}
      autoPromotionEnabled: {{ .Values.rollout.strategy.blueGreen.autoPromotionEnabled }}
      scaleDownDelaySeconds: {{ .Values.rollout.strategy.blueGreen.scaleDownDelaySeconds }}
      previewReplicaCount: {{ .Values.rollout.strategy.blueGreen.previewReplicaCount }}
      {{- with .Values.rollout.strategy.blueGreen.antiAffinity }}
      antiAffinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
