---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.rollout.strategy.blueGreen.activeService }}
  labels:
    {{- include "rollout-app.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "rollout-app.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.rollout.strategy.blueGreen.previewService }}
  labels:
    {{- include "rollout-app.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "rollout-app.selectorLabels" . | nindent 4 }}
