---
# Frontend Active Service
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.frontend.rollout.strategy.blueGreen.activeService }}
  labels:
    {{- include "rollout-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: {{ .Values.frontend.service.targetPort }}
      protocol: TCP
      name: http
      {{- if eq .Values.frontend.service.type "NodePort" }}
      nodePort: {{ .Values.frontend.service.nodePort }}
      {{- end }}
  selector:
    {{- include "rollout-app.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
---
# Frontend Preview Service
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.frontend.rollout.strategy.blueGreen.previewService }}
  labels:
    {{- include "rollout-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: {{ .Values.frontend.service.targetPort }}
      protocol: TCP
      name: http
      {{- if eq .Values.frontend.service.type "NodePort" }}
      nodePort: {{ add .Values.frontend.service.nodePort 100 }}
      {{- end }}
  selector:
    {{- include "rollout-app.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
---
# Backend Active Service
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.backend.rollout.strategy.blueGreen.activeService }}
  labels:
    {{- include "rollout-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  type: {{ .Values.backend.service.type }}
  ports:
    - port: {{ .Values.backend.service.port }}
      targetPort: {{ .Values.backend.service.targetPort }}
      protocol: TCP
      name: http
      {{- if eq .Values.backend.service.type "NodePort" }}
      nodePort: {{ .Values.backend.service.nodePort }}
      {{- end }}
  selector:
    {{- include "rollout-app.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: backend
---
# Backend Preview Service
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.backend.rollout.strategy.blueGreen.previewService }}
  labels:
    {{- include "rollout-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  type: {{ .Values.backend.service.type }}
  ports:
    - port: {{ .Values.backend.service.port }}
      targetPort: {{ .Values.backend.service.targetPort }}
      protocol: TCP
      name: http
      {{- if eq .Values.backend.service.type "NodePort" }}
      nodePort: {{ add .Values.backend.service.nodePort 100 }}
      {{- end }}
  selector:
    {{- include "rollout-app.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: backend
