apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: akuity-argocd-application-controller-himesh-corp-mac
  namespace: argocd
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  - configmaps
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - argoproj.io
  resources:
  - applications
  - applicationsets
  - appprojects
  verbs:
  - create
  - get
  - list
  - watch
  - update
  - patch
  - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: akuity-argocd-application-controller-himesh-corp-mac
  namespace: argocd
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: akuity-argocd-application-controller-himesh-corp-mac
subjects:
- kind: ServiceAccount
  name: akuity-argocd-application-controller-himesh-corp-mac
  namespace: argocd
