apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apollo-app-of-apps
  annotations:
    notifications.argoproj.io/subscribe.on-sync-succeeded.slack.slack: hp-slack-ak-test
spec:
  destination:
    name: himesh-corp-mac
    namespace: argocd
  source:
    path: apollo-app/apps
    repoURL: https://github.com/himeshpanc/rocket-apps.git
    targetRevision: HEAD
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true