apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: slack-test-app
  namespace: akuity  # Important: This should be in the akuity namespace
  annotations:
    notifications.argoproj.io/subscribe.on-sync-succeeded.slack.slack: hp-slack-ak-test
spec:
  destination:
    name: himesh-corp-mac  # Your cluster name in Akuity
    namespace: slack-test
  source:
    path: slack-test-app
    repoURL: https://github.com/himeshpanc/rocket-apps.git
    targetRevision: HEAD
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
