apiVersion: apps/v1
kind: Deployment
metadata:
  name: slack-test-app
  namespace: slack-test
spec:
  selector:
    matchLabels:
      app: slack-test-app
  replicas: 1
  template:
    metadata:
      labels:
        app: slack-test-app
    spec:
      containers:
      - name: nginx
        image: nginx:1.25.3
        ports:
        - containerPort: 80
