apiVersion: v1
kind: Service
metadata:
  labels:
    app: lunar-app-sc
  name: lunar-app-sc-service
spec:
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: lunar-app-sc
  type: NodePort