apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: test-secret
  namespace: sync-window-test
spec:
  refreshInterval: 1s
  secretStoreRef:
    name: nonexistent-store    # This will cause failure
    kind: ClusterSecretStore
  target:
    name: test-secret
  data:
    - secretKey: test-key
      remoteRef:
        key: nonexistent-key   # This will cause failure
