apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: test-app
spec:
  components:
    - name: test-ns
      type: namespace
      properties:
        name: test-ns-dev
    - name: backend
      type: webservice
      properties:
        image: himeshp/lunar-app:v2
        ports:
          - port: 3000
            expose: true
      traits:
        - type: scaler
          properties:
            replicas: 1
