apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apollo-dev
  annotations:
    notifications.argoproj.io/subscribe.on-sync-succeeded.slack: hp-slack-ak-test
spec:
  destination:
    name: himesh-corp-mac
    namespace: dev
  source:
    path: apollo-app/charts/apollo
    repoURL: https://github.com/himeshpanc/rocket-apps.git
    targetRevision: HEAD
    helm:
      valueFiles:
      - values-dev.yaml
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true  
    syncOptions:
      - CreateNamespace=true