apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test-validation
  namespace: argocd
spec:
  project: default
  source:
    repoURL: <YOUR_REPO_URL>
    targetRevision: HEAD
    path: mychart
    helm:
      values: |
        config: null
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true