apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test-validation
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/himeshpanc/rocket-apps
    targetRevision: main
    path: test-chart/mychart
    helm:
      values: |
        config:
          key1: value1
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true