replicaCount: 2

image:
  tag: qa-latest

rollout:
  strategy:
    blueGreen:
      autoPromotionEnabled: false  # Manual promotion in QA for testing
      scaleDownDelaySeconds: 60    # Longer delay for testing
      previewReplicaCount: 1

resources:
  limits:
    cpu: 750m
    memory: 768Mi
  requests:
    cpu: 375m
    memory: 384Mi
