nameOverride: ""
fullnameOverride: "argo-rollouts-app"

backend:
  replicaCount: 1
  image:
    repository: himeshp/lunar-app
    tag: v2
    pullPolicy: Always
  service:
    type: NodePort
    port: 3000
    targetPort: 3000
    nodePort: 31000
  resources:
    limits:
      cpu: 300m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi
  rollout:
    strategy:
      blueGreen:
        activeService: argo-rollouts-app-backend-active
        previewService: argo-rollouts-app-backend-preview
        autoPromotionEnabled: false
        scaleDownDelaySeconds: 30
        previewReplicaCount: 1

frontend:
  replicaCount: 1
  image:
    repository: himeshp/react-app
    tag: latest
    pullPolicy: Always
  service:
    type: NodePort
    port: 3003
    targetPort: 3003
    nodePort: 31001
  resources:
    limits:
      cpu: 300m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi
  rollout:
    strategy:
      blueGreen:
        activeService: argo-rollouts-app-frontend-active
        previewService: argo-rollouts-app-frontend-preview
        autoPromotionEnabled: false
        scaleDownDelaySeconds: 30
        previewReplicaCount: 1
