frontend:
  replicaCount: 2
  image:
    tag: qa-latest
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 250m
      memory: 256Mi
  rollout:
    strategy:
      blueGreen:
        autoPromotionEnabled: false
        scaleDownDelaySeconds: 60

backend:
  replicaCount: 2
  image:
    tag: qa-latest
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 250m
      memory: 256Mi
  rollout:
    strategy:
      blueGreen:
        autoPromotionEnabled: false
        scaleDownDelaySeconds: 60
