apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: test-appset
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - env: dev
  template:
    metadata:
      name: test-app-{{.env}}
    spec:
      project: default
      sources:
        - repoURL: https://github.com/himeshpanc/rocket-apps.git
          path: "argocd-annotations-test/overlays/{{.env}}"
          targetRevision: main
          plugin:
            name: oam-v1.0
          annotations:
            argocd.argoproj.io/sync-wave: "-1"
        - repoURL: https://github.com/himeshpanc/rocket-apps.git
          path: "argocd-annotations-test/overlays/{{.env}}"
          targetRevision: main
          kustomize:
            commonAnnotationsEnvsubst: true
            commonAnnotations:
              ARGOCD_APP_NAME: ${ARGOCD_APP_NAME}
          annotations:
            argocd.argoproj.io/sync-wave: "1"
      destination:
        server: https://kubernetes.default.svc
        namespace: test-ns-{{.env}}