apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: test-appset
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - env: dev
  template:
    metadata:
      name: test-app-{{.env}}
    spec:
      project: default
      sources:
        - repoURL: https://github.com/himeshpanc/rocket-apps
          path: argocd-annotations-test/overlays/{{.env}}
          targetRevision: main
          plugin:
            name: oam-v1.0
          annotations:
            argocd.argoproj.io/sync-wave: "-1"
        - repoURL: https://github.com/himeshpanc/rocket-apps
          path: argocd-annotations-test/overlays/{{.env}}
          targetRevision: main
          kustomize:
            commonAnnotationsEnvsubst: true
            commonAnnotations:
              ARGOCD_APP_NAME: ${ARGOCD_APP_NAME}
              TARGET_ENVIRONMENT: "{{.env}}"
              ARGOCD_APP_NAMESPACE: ${ARGOCD_APP_NAMESPACE}
              ARGOCD_APP_SOURCE_PATH: ${ARGOCD_APP_SOURCE_PATH}
              ARGOCD_APP_SOURCE_REPO_URL: ${ARGOCD_APP_SOURCE_REPO_URL}
              ARGOCD_APP_SOURCE_TARGET_REVISION: ${ARGOCD_APP_SOURCE_TARGET_REVISION}
          annotations:
            argocd.argoproj.io/sync-wave: "1"
      destination:
        server: https://kubernetes.default.svc
        namespace: test-ns-{{.env}}