apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: test-appset
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - env: dev
  template:
    metadata:
      name: test-app-{{.env}}
    spec:
      project: default
      source:
        plugin:
          name: oam-v1.0
          env:
          - name: ARGOCD_APP_NAME
            value: test-app-{{.env}}
        repoURL: https://github.com/himeshpanc/rocket-apps.git
        targetRevision: HEAD
        path: argocd-annotations-test/overlays/{{.env}}
      destination:
        server: https://kubernetes.default.svc
        namespace: test-ns-{{.env}}
      syncPolicy:
        automated:
          prune: true
          selfHeal: true