apiVersion: core.oam.dev/v1alpha2
kind: ApplicationConfiguration
metadata:
  name: backend-app
spec:
  components:
    - componentName: backend
      traits:
        - trait:
            apiVersion: core.oam.dev/v1alpha2
            kind: ManualScalerTrait
            spec:
              replicaCount: 1
