apiVersion: core.oam.dev/v1alpha2
kind: Component
metadata:
  name: backend
spec:
  workload:
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: backend
      annotations:
        TEST_ANNOTATION: "oam-annotation"  # This should override kustomize's annotation
    spec:
      replicas: 1
      selector:
        matchLabels:
          app: backend
      template:
        metadata:
          labels:
            app: backend
          annotations:
            TEST_ANNOTATION: "oam-annotation"  # Also add to pod template
        spec:
          containers:
            - name: backend
              image: himeshp/lunar-app:v2
              imagePullPolicy: Always
              ports:
                - containerPort: 3000
              resources:
                limits:
                  cpu: "300m"
                  memory: "256Mi"
                requests:
                  cpu: "100m"
                  memory: "128Mi"
