apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
patches:
  - target:
      kind: Application
      name: test-app
    patch: |-
      - op: add
        path: /metadata/annotations
        value:
          ARGOCD_APP_NAME: ${ARGOCD_APP_NAME}
          TEST_ANNOTATION: "kustomize-annotation"
