backend:
  replicaCount: 1
  image:
    repository: himeshp/lunar-app
    tag: v2
    pullPolicy: Always
  service:
    type: NodePort
    port: 3000
    targetPort: 3000
    nodePort: 30000
  resources:
    limits:
      cpu: 300m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi
