apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rollout-app-qa
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/himeshpanc/rocket-apps.git
    path: argo-rollout-app/charts/rollout-app
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
        - values-qa.yaml
      parameters:
        - name: frontend.service.nodePort
          value: "32001"
        - name: backend.service.nodePort
          value: "32000"
  destination:
    server: https://kubernetes.default.svc
    namespace: rollout-app-qa
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
