apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sync-window-test
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/himeshpanc/rocket-apps.git
    targetRevision: HEAD
    path: argocd-sync-window-test/manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: sync-window-test
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 10
      backoff:
        duration: 2s
        factor: 1
        maxDuration: 10s
