apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rollout-app-parent
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/himeshpanc/rocket-apps.git
    path: argo-rollout-app/apps
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
